title: Michael Fabila
logo: "FB_IMG_1513128567692.jpg" #
description: > # your text below (remove <br> elements if you don't need line breaks)
  Optimistic Student on the road to success. 
  <br><br>
  Everyone deserves a second chance
  <br><br>
  <a href="https://www.linkedin.com/in/mikefab/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

