title: Michael Fabila
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Optimistic Student on the road to success. 
  <br><br>
  Everyone deserves a second chance
  <br><br>
  <a href="https://www.linkedin.com/in/mikefab/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

